// Refresh dist/provincial-draws.js from the official provincial invitation pages.
// Usage: node scripts/fetch-draws.mjs [--check]
//   --check  exit 1 if the generated file would change (no write).
// A source that fails to fetch or parse keeps its previous data and is reported; the script exits 2 when every
// source fails so CI notices a systemic problem (network, blocking) rather than silently going stale.
import {readFile,writeFile} from 'node:fs/promises';
import {SOURCES,selectRecent} from './draws/sources.mjs';

const OUT=new URL('../dist/provincial-draws.js',import.meta.url);
const check=process.argv.includes('--check');
const annotate=(level,msg)=>console.log(process.env.GITHUB_ACTIONS?`::${level}::${msg}`:`${level}: ${msg}`);

async function previous(){try{return (await import(OUT.href+'?'+Date.now())).provincialDraws;}catch{return {};}}

async function fetchSource(id,{url,parse}){
 const res=await fetch(url,{headers:{'user-agent':'pr-score-draw-fetcher/1.0 (+https://pr.zhengqiu.net)','accept':'text/html'},signal:AbortSignal.timeout(30000)});
 if(!res.ok)throw new Error(`${id}: HTTP ${res.status}`);
 const {updated,rounds}=parse(await res.text());
 return {updated,url,rounds:selectRecent(rounds)};
}

const prev=await previous(),next={};let failures=0;
for(const [id,source] of Object.entries(SOURCES)){
 try{next[id]=await fetchSource(id,source);console.log(`${id}: ${next[id].rounds.length} rounds, updated ${next[id].updated??'unknown'}`);}
 catch(err){failures++;annotate('warning',`${id} kept previous data: ${err.message}`);if(prev[id])next[id]=prev[id];}
}
if(failures===Object.keys(SOURCES).length){annotate('error','Every draw source failed');process.exit(2);}

const body=`// Generated by scripts/fetch-draws.mjs from the official provincial invitation pages. Do not edit by hand;\n// run \`npm run draws\` (or wait for the scheduled GitHub Action) to refresh.\nexport const provincialDraws=${JSON.stringify(next,null,1)};\n`;
const current=await readFile(OUT,'utf8').catch(()=>'');
if(body===current){console.log('No changes.');process.exit(0);}
if(check){console.log('Draw data is out of date.');process.exit(1);}
await writeFile(OUT,body);console.log(`Wrote ${OUT.pathname}`);
